[project]
name = "gestureflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.14",
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.3",
]
